# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='image_url',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
