# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import recognizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0002_auto_20180219_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevealData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('image_url', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='facedata',
            name='image_url',
            field=models.ImageField(blank=True, default='default.png', upload_to=recognizer.models.content_file_name),
        ),
    ]
