# Generated by Django 2.0.2 on 2018-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0003_auto_20180220_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='face_encoding',
            field=models.TextField(),
        ),
    ]
