# Generated by Django 2.0.2 on 2018-04-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0004_auto_20180310_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedata',
            name='face_encoding',
            field=models.TextField(default='facereconz'),
        ),
    ]
