# Generated by Django 2.0.2 on 2018-04-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0005_auto_20180413_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='revealdata',
            name='age_group',
            field=models.CharField(default='undetected', max_length=100),
        ),
        migrations.AddField(
            model_name='revealdata',
            name='anger',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='revealdata',
            name='disgust',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='revealdata',
            name='fear',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='revealdata',
            name='joy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='revealdata',
            name='sadness',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='revealdata',
            name='surprise',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
