# Generated by Django 2.1.7 on 2019-09-22 18:22

from django.db import migrations, models
import recognizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0006_auto_20180414_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revealdata',
            name='anger',
        ),
        migrations.RemoveField(
            model_name='revealdata',
            name='disgust',
        ),
        migrations.RemoveField(
            model_name='revealdata',
            name='fear',
        ),
        migrations.RemoveField(
            model_name='revealdata',
            name='joy',
        ),
        migrations.RemoveField(
            model_name='revealdata',
            name='sadness',
        ),
        migrations.RemoveField(
            model_name='revealdata',
            name='status',
        ),
        migrations.RemoveField(
            model_name='revealdata',
            name='surprise',
        ),
        migrations.AlterField(
            model_name='revealdata',
            name='image_url',
            field=models.ImageField(blank=True, default='default.png', upload_to=recognizer.models.revealFace_file_name),
        ),
    ]
